// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/gateway/api/accounts/accounts.proto

/*
Package accounts is a generated protocol buffer package.

It is generated from these files:
	components/gateway/api/accounts/accounts.proto

It has these top-level messages:
*/
package accounts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import hurtlocker_sessionsrv_accounts_request "github.com/chuckleheads/hurtlocker/components/sessionsrv/accounts/request"
import hurtlocker_sessionsrv_accounts_response "github.com/chuckleheads/hurtlocker/components/sessionsrv/accounts/response"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Accounts service

type AccountsClient interface {
	GetAccount(ctx context.Context, in *hurtlocker_sessionsrv_accounts_request.GetAccountReq, opts ...grpc.CallOption) (*hurtlocker_sessionsrv_accounts_response.AccountResp, error)
	CreateAccount(ctx context.Context, in *hurtlocker_sessionsrv_accounts_request.CreateAccountReq, opts ...grpc.CallOption) (*hurtlocker_sessionsrv_accounts_response.AccountResp, error)
	UpdateAccount(ctx context.Context, in *hurtlocker_sessionsrv_accounts_request.UpdateAccountReq, opts ...grpc.CallOption) (*hurtlocker_sessionsrv_accounts_response.AccountResp, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) GetAccount(ctx context.Context, in *hurtlocker_sessionsrv_accounts_request.GetAccountReq, opts ...grpc.CallOption) (*hurtlocker_sessionsrv_accounts_response.AccountResp, error) {
	out := new(hurtlocker_sessionsrv_accounts_response.AccountResp)
	err := grpc.Invoke(ctx, "/hurtlocker.api.accounts.Accounts/GetAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) CreateAccount(ctx context.Context, in *hurtlocker_sessionsrv_accounts_request.CreateAccountReq, opts ...grpc.CallOption) (*hurtlocker_sessionsrv_accounts_response.AccountResp, error) {
	out := new(hurtlocker_sessionsrv_accounts_response.AccountResp)
	err := grpc.Invoke(ctx, "/hurtlocker.api.accounts.Accounts/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdateAccount(ctx context.Context, in *hurtlocker_sessionsrv_accounts_request.UpdateAccountReq, opts ...grpc.CallOption) (*hurtlocker_sessionsrv_accounts_response.AccountResp, error) {
	out := new(hurtlocker_sessionsrv_accounts_response.AccountResp)
	err := grpc.Invoke(ctx, "/hurtlocker.api.accounts.Accounts/UpdateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Accounts service

type AccountsServer interface {
	GetAccount(context.Context, *hurtlocker_sessionsrv_accounts_request.GetAccountReq) (*hurtlocker_sessionsrv_accounts_response.AccountResp, error)
	CreateAccount(context.Context, *hurtlocker_sessionsrv_accounts_request.CreateAccountReq) (*hurtlocker_sessionsrv_accounts_response.AccountResp, error)
	UpdateAccount(context.Context, *hurtlocker_sessionsrv_accounts_request.UpdateAccountReq) (*hurtlocker_sessionsrv_accounts_response.AccountResp, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hurtlocker_sessionsrv_accounts_request.GetAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hurtlocker.api.accounts.Accounts/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccount(ctx, req.(*hurtlocker_sessionsrv_accounts_request.GetAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hurtlocker_sessionsrv_accounts_request.CreateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hurtlocker.api.accounts.Accounts/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CreateAccount(ctx, req.(*hurtlocker_sessionsrv_accounts_request.CreateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hurtlocker_sessionsrv_accounts_request.UpdateAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hurtlocker.api.accounts.Accounts/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdateAccount(ctx, req.(*hurtlocker_sessionsrv_accounts_request.UpdateAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hurtlocker.api.accounts.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _Accounts_GetAccount_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _Accounts_CreateAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _Accounts_UpdateAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/gateway/api/accounts/accounts.proto",
}

func init() { proto.RegisterFile("components/gateway/api/accounts/accounts.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcd, 0x4a, 0x33, 0x31,
	0x14, 0x86, 0x99, 0xef, 0x03, 0xd1, 0x40, 0x5d, 0x84, 0xa2, 0x38, 0x14, 0x84, 0x2e, 0xbb, 0x48,
	0xa0, 0x5a, 0x91, 0xee, 0xac, 0x82, 0x7b, 0xc1, 0x8d, 0xbb, 0x34, 0x3d, 0xcc, 0x0c, 0x9d, 0xe6,
	0xa4, 0xf9, 0x51, 0x44, 0xdc, 0x78, 0x0b, 0x22, 0x6e, 0xbd, 0x27, 0x2f, 0xc0, 0x8d, 0x17, 0x22,
	0x33, 0x9d, 0x9f, 0xb6, 0x08, 0x23, 0xb3, 0x4b, 0xce, 0xe1, 0xc9, 0xfb, 0x9c, 0x70, 0x08, 0x93,
	0xb8, 0xd0, 0xa8, 0x40, 0x39, 0xcb, 0x23, 0xe1, 0xe0, 0x41, 0x3c, 0x72, 0xa1, 0x13, 0x2e, 0xa4,
	0x44, 0x9f, 0x15, 0xcb, 0x03, 0xd3, 0x06, 0x1d, 0xd2, 0xc3, 0xd8, 0x1b, 0x97, 0xa2, 0x9c, 0x83,
	0x61, 0x42, 0x27, 0xac, 0x6c, 0x87, 0xbd, 0x08, 0x31, 0x4a, 0x61, 0x05, 0x2b, 0x85, 0x4e, 0xb8,
	0x04, 0x55, 0x81, 0x85, 0xa3, 0xb5, 0x18, 0x0b, 0xd6, 0x66, 0x2d, 0x73, 0x5f, 0xa7, 0x18, 0x58,
	0x7a, 0xb0, 0x6e, 0x2b, 0x2d, 0x3c, 0x6b, 0xc4, 0xac, 0x46, 0x65, 0x61, 0x8b, 0x1b, 0x7e, 0xfd,
	0x27, 0xbb, 0x17, 0x45, 0x89, 0xbe, 0x07, 0x84, 0x5c, 0x83, 0x2b, 0xee, 0x74, 0xc4, 0xd6, 0x46,
	0xa8, 0x1f, 0xad, 0x26, 0x61, 0x85, 0x0b, 0xab, 0x99, 0x1b, 0x58, 0x86, 0xa7, 0xcd, 0xd8, 0xca,
	0x85, 0x55, 0x90, 0xd5, 0xfd, 0xde, 0xcb, 0xe7, 0xf7, 0xeb, 0xbf, 0x03, 0xda, 0xad, 0x9d, 0x9f,
	0xbc, 0x05, 0xa3, 0xc4, 0x02, 0x9e, 0xe9, 0x5b, 0x40, 0x3a, 0x97, 0x06, 0x84, 0x83, 0x52, 0xee,
	0xfc, 0xaf, 0x72, 0x1b, 0x58, 0x7b, 0xbf, 0x6e, 0xee, 0xb7, 0xdf, 0xdf, 0xab, 0xfc, 0xc6, 0xc1,
	0x80, 0x7e, 0x04, 0xa4, 0x73, 0xab, 0x67, 0x6d, 0xbc, 0x36, 0xb0, 0xf6, 0x5e, 0xc7, 0xb9, 0xd7,
	0xd1, 0xf0, 0xd7, 0x7f, 0x1b, 0x07, 0x83, 0xc9, 0xd5, 0xdd, 0x24, 0x4a, 0x5c, 0xec, 0xa7, 0xd9,
	0x02, 0x73, 0x19, 0x7b, 0x39, 0x4f, 0x21, 0x06, 0x31, 0xb3, 0xbc, 0xce, 0xe3, 0x0d, 0xcb, 0x3d,
	0xdd, 0xc9, 0xd7, 0xe5, 0xe4, 0x27, 0x00, 0x00, 0xff, 0xff, 0x17, 0xbb, 0xd3, 0x80, 0x06, 0x03,
	0x00, 0x00,
}
