// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/jobsrv/jobs/request/jobs.proto

/*
Package request is a generated protocol buffer package.

It is generated from these files:
	components/jobsrv/jobs/request/jobs.proto

It has these top-level messages:
	Job
	GetJobsReq
	GetJobReq
	CreateJobReq
*/
package request

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetJobsReq struct {
}

func (m *GetJobsReq) Reset()                    { *m = GetJobsReq{} }
func (m *GetJobsReq) String() string            { return proto.CompactTextString(m) }
func (*GetJobsReq) ProtoMessage()               {}
func (*GetJobsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetJobReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetJobReq) Reset()                    { *m = GetJobReq{} }
func (m *GetJobReq) String() string            { return proto.CompactTextString(m) }
func (*GetJobReq) ProtoMessage()               {}
func (*GetJobReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetJobReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateJobReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateJobReq) Reset()                    { *m = CreateJobReq{} }
func (m *CreateJobReq) String() string            { return proto.CompactTextString(m) }
func (*CreateJobReq) ProtoMessage()               {}
func (*CreateJobReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateJobReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "hurtlocker.jobsrv.jobs.request.Job")
	proto.RegisterType((*GetJobsReq)(nil), "hurtlocker.jobsrv.jobs.request.GetJobsReq")
	proto.RegisterType((*GetJobReq)(nil), "hurtlocker.jobsrv.jobs.request.GetJobReq")
	proto.RegisterType((*CreateJobReq)(nil), "hurtlocker.jobsrv.jobs.request.CreateJobReq")
}

func init() { proto.RegisterFile("components/jobsrv/jobs/request/jobs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xcf, 0xbd, 0x6e, 0x83, 0x30,
	0x14, 0x05, 0x60, 0x41, 0xab, 0x4a, 0x5c, 0xa1, 0x0e, 0x9e, 0x98, 0xda, 0xca, 0x53, 0x59, 0xec,
	0xa1, 0x4f, 0xd0, 0x30, 0x44, 0x62, 0x64, 0xcc, 0x86, 0xcd, 0x55, 0x4c, 0xf8, 0xb9, 0xe0, 0x9f,
	0x3c, 0x7f, 0x24, 0x13, 0x25, 0x59, 0x92, 0xe9, 0xf8, 0x58, 0xdf, 0x70, 0x0f, 0x94, 0x9a, 0xa6,
	0x85, 0x66, 0x9c, 0xbd, 0x93, 0x27, 0x52, 0xce, 0x9e, 0x63, 0x48, 0x8b, 0x6b, 0x40, 0xe7, 0x63,
	0x11, 0x8b, 0x25, 0x4f, 0xec, 0xcb, 0x04, 0xeb, 0x47, 0xd2, 0x03, 0x5a, 0xb1, 0xd1, 0x18, 0xe2,
	0x4a, 0x79, 0x09, 0x6f, 0x35, 0x29, 0xf6, 0x09, 0x69, 0xdf, 0x15, 0xc9, 0x4f, 0xf2, 0x9b, 0x35,
	0x69, 0xdf, 0x31, 0x06, 0xef, 0x73, 0x3b, 0x61, 0x91, 0xc6, 0x9f, 0xf8, 0xe6, 0x39, 0xc0, 0x1e,
	0x7d, 0x4d, 0xca, 0x35, 0xb8, 0xf2, 0x6f, 0xc8, 0xb6, 0xd6, 0xe0, 0x7a, 0xe3, 0xc9, 0x03, 0xe7,
	0x90, 0x57, 0x16, 0x5b, 0x8f, 0xcf, 0xcd, 0xae, 0x3a, 0xfc, 0x1f, 0x7b, 0x6f, 0x82, 0x12, 0x9a,
	0x26, 0xa9, 0x4d, 0xd0, 0xc3, 0x88, 0x06, 0xdb, 0xce, 0xc9, 0xfb, 0xdd, 0xf2, 0xf5, 0x5a, 0xf5,
	0x11, 0x97, 0xfe, 0x5d, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x24, 0xb0, 0x86, 0x16, 0x01, 0x00,
	0x00,
}
