// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/originsrv/api/projects/projects.proto

/*
Package projects is a generated protocol buffer package.

It is generated from these files:
	components/originsrv/api/projects/projects.proto

It has these top-level messages:
*/
package projects

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import hurtlocker_originsrv_projects_request "github.com/chuckleheads/hurtlocker/components/originsrv/projects/request"
import hurtlocker_originsrv_projects_response "github.com/chuckleheads/hurtlocker/components/originsrv/projects/response"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Projects service

type ProjectsClient interface {
	GetProject(ctx context.Context, in *hurtlocker_originsrv_projects_request.GetProjectReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_projects_response.ProjectResp, error)
	CreateProject(ctx context.Context, in *hurtlocker_originsrv_projects_request.CreateProjectReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_projects_response.ProjectResp, error)
	UpdateProject(ctx context.Context, in *hurtlocker_originsrv_projects_request.UpdateProjectReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_projects_response.ProjectResp, error)
}

type projectsClient struct {
	cc *grpc.ClientConn
}

func NewProjectsClient(cc *grpc.ClientConn) ProjectsClient {
	return &projectsClient{cc}
}

func (c *projectsClient) GetProject(ctx context.Context, in *hurtlocker_originsrv_projects_request.GetProjectReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_projects_response.ProjectResp, error) {
	out := new(hurtlocker_originsrv_projects_response.ProjectResp)
	err := grpc.Invoke(ctx, "/hurtlocker.originsrv.projects.Projects/GetProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) CreateProject(ctx context.Context, in *hurtlocker_originsrv_projects_request.CreateProjectReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_projects_response.ProjectResp, error) {
	out := new(hurtlocker_originsrv_projects_response.ProjectResp)
	err := grpc.Invoke(ctx, "/hurtlocker.originsrv.projects.Projects/CreateProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsClient) UpdateProject(ctx context.Context, in *hurtlocker_originsrv_projects_request.UpdateProjectReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_projects_response.ProjectResp, error) {
	out := new(hurtlocker_originsrv_projects_response.ProjectResp)
	err := grpc.Invoke(ctx, "/hurtlocker.originsrv.projects.Projects/UpdateProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Projects service

type ProjectsServer interface {
	GetProject(context.Context, *hurtlocker_originsrv_projects_request.GetProjectReq) (*hurtlocker_originsrv_projects_response.ProjectResp, error)
	CreateProject(context.Context, *hurtlocker_originsrv_projects_request.CreateProjectReq) (*hurtlocker_originsrv_projects_response.ProjectResp, error)
	UpdateProject(context.Context, *hurtlocker_originsrv_projects_request.UpdateProjectReq) (*hurtlocker_originsrv_projects_response.ProjectResp, error)
}

func RegisterProjectsServer(s *grpc.Server, srv ProjectsServer) {
	s.RegisterService(&_Projects_serviceDesc, srv)
}

func _Projects_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hurtlocker_originsrv_projects_request.GetProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hurtlocker.originsrv.projects.Projects/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).GetProject(ctx, req.(*hurtlocker_originsrv_projects_request.GetProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_CreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hurtlocker_originsrv_projects_request.CreateProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).CreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hurtlocker.originsrv.projects.Projects/CreateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).CreateProject(ctx, req.(*hurtlocker_originsrv_projects_request.CreateProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Projects_UpdateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hurtlocker_originsrv_projects_request.UpdateProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServer).UpdateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hurtlocker.originsrv.projects.Projects/UpdateProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServer).UpdateProject(ctx, req.(*hurtlocker_originsrv_projects_request.UpdateProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Projects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hurtlocker.originsrv.projects.Projects",
	HandlerType: (*ProjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProject",
			Handler:    _Projects_GetProject_Handler,
		},
		{
			MethodName: "CreateProject",
			Handler:    _Projects_CreateProject_Handler,
		},
		{
			MethodName: "UpdateProject",
			Handler:    _Projects_UpdateProject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/originsrv/api/projects/projects.proto",
}

func init() { proto.RegisterFile("components/originsrv/api/projects/projects.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x4a, 0x33, 0x31,
	0x14, 0xc7, 0x99, 0x8f, 0x0f, 0xd1, 0x40, 0x5d, 0x04, 0x57, 0x83, 0x2e, 0xac, 0x2b, 0xbb, 0x48,
	0xb4, 0xad, 0x0a, 0xc5, 0x95, 0x8a, 0x6e, 0x45, 0x70, 0xe3, 0x46, 0xd2, 0xf4, 0x31, 0x33, 0xb6,
	0x93, 0x97, 0x26, 0x19, 0x37, 0xa5, 0x1b, 0x3d, 0x42, 0x6f, 0xe0, 0x35, 0x3c, 0x86, 0x57, 0xf0,
	0x20, 0xc2, 0x34, 0x9d, 0x71, 0x8a, 0x38, 0x32, 0xbb, 0x97, 0x47, 0x7e, 0x79, 0xbf, 0xfc, 0x49,
	0xc8, 0x91, 0xc4, 0x54, 0xa3, 0x02, 0xe5, 0x2c, 0x47, 0x93, 0x44, 0x89, 0xb2, 0xe6, 0x99, 0x0b,
	0x9d, 0x70, 0x6d, 0xf0, 0x09, 0xa4, 0xb3, 0x45, 0xc1, 0xb4, 0x41, 0x87, 0x74, 0x2f, 0xce, 0x8c,
	0x9b, 0xa0, 0x1c, 0x83, 0x61, 0x05, 0xc1, 0x56, 0x9b, 0xc2, 0xdd, 0x08, 0x31, 0x9a, 0x40, 0x7e,
	0x84, 0x50, 0x0a, 0x9d, 0x70, 0x09, 0x2a, 0x0f, 0x87, 0xfd, 0x1f, 0xc7, 0x15, 0xa3, 0x0c, 0x4c,
	0x33, 0xb0, 0x6e, 0x6d, 0x64, 0x78, 0x52, 0x47, 0x59, 0x8d, 0xca, 0xc2, 0x1a, 0xd6, 0x7d, 0xfd,
	0x4f, 0x36, 0x6f, 0x7d, 0x8b, 0xbe, 0x05, 0x84, 0xdc, 0x80, 0xf3, 0x6b, 0xda, 0x67, 0xbf, 0x5e,
	0x83, 0x79, 0x13, 0x56, 0x22, 0x77, 0x30, 0x0d, 0x7b, 0xb5, 0xd4, 0xd2, 0x84, 0x15, 0x8c, 0xd5,
	0xed, 0xc3, 0x97, 0x8f, 0xcf, 0xc5, 0xbf, 0x03, 0xba, 0x5f, 0x1a, 0xcf, 0x96, 0xec, 0x9c, 0xcf,
	0xb4, 0x90, 0x63, 0x11, 0xc1, 0xa3, 0x12, 0x29, 0xcc, 0xe9, 0x22, 0x20, 0xad, 0x4b, 0x03, 0xc2,
	0xc1, 0xca, 0xf3, 0xec, 0x8f, 0x9e, 0x15, 0xaa, 0xb1, 0xea, 0x4e, 0xae, 0xba, 0xdd, 0xde, 0x2a,
	0x54, 0x07, 0x41, 0x87, 0xbe, 0x07, 0xa4, 0x75, 0xaf, 0x47, 0x0d, 0xac, 0x2a, 0x54, 0x63, 0xab,
	0xf3, 0xdc, 0xea, 0xb4, 0x7b, 0xfc, 0x2d, 0x40, 0x5f, 0xb1, 0x32, 0x48, 0xdf, 0xa8, 0x04, 0x3a,
	0x08, 0x3a, 0x17, 0xd7, 0x0f, 0x57, 0x51, 0xe2, 0xe2, 0x6c, 0xc8, 0x24, 0xa6, 0x5c, 0xc6, 0x99,
	0x1c, 0x4f, 0x20, 0x06, 0x31, 0xb2, 0xbc, 0x74, 0xe1, 0xb5, 0xdf, 0x60, 0xb8, 0x91, 0x3f, 0xaa,
	0xde, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0x7a, 0x63, 0x8f, 0x32, 0x03, 0x00, 0x00,
}
