// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/builder-gateway/api/origins/request/origins.proto

/*
Package request is a generated protocol buffer package.

It is generated from these files:
	components/builder-gateway/api/origins/request/origins.proto

It has these top-level messages:
	Origin
	GetOriginsReq
	GetOriginReq
	CreateOriginReq
	UpdateOriginReq
*/
package request

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Origin struct {
	Id                       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	DefaultPackageVisibility string `protobuf:"bytes,3,opt,name=default_package_visibility,json=defaultPackageVisibility" json:"default_package_visibility,omitempty"`
}

func (m *Origin) Reset()                    { *m = Origin{} }
func (m *Origin) String() string            { return proto.CompactTextString(m) }
func (*Origin) ProtoMessage()               {}
func (*Origin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Origin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Origin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Origin) GetDefaultPackageVisibility() string {
	if m != nil {
		return m.DefaultPackageVisibility
	}
	return ""
}

type GetOriginsReq struct {
}

func (m *GetOriginsReq) Reset()                    { *m = GetOriginsReq{} }
func (m *GetOriginsReq) String() string            { return proto.CompactTextString(m) }
func (*GetOriginsReq) ProtoMessage()               {}
func (*GetOriginsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetOriginReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetOriginReq) Reset()                    { *m = GetOriginReq{} }
func (m *GetOriginReq) String() string            { return proto.CompactTextString(m) }
func (*GetOriginReq) ProtoMessage()               {}
func (*GetOriginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetOriginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateOriginReq struct {
	Name                     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DefaultPackageVisibility string `protobuf:"bytes,2,opt,name=default_package_visibility,json=defaultPackageVisibility" json:"default_package_visibility,omitempty"`
}

func (m *CreateOriginReq) Reset()                    { *m = CreateOriginReq{} }
func (m *CreateOriginReq) String() string            { return proto.CompactTextString(m) }
func (*CreateOriginReq) ProtoMessage()               {}
func (*CreateOriginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateOriginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOriginReq) GetDefaultPackageVisibility() string {
	if m != nil {
		return m.DefaultPackageVisibility
	}
	return ""
}

type UpdateOriginReq struct {
	Name                     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	DefaultPackageVisibility string `protobuf:"bytes,2,opt,name=default_package_visibility,json=defaultPackageVisibility" json:"default_package_visibility,omitempty"`
}

func (m *UpdateOriginReq) Reset()                    { *m = UpdateOriginReq{} }
func (m *UpdateOriginReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateOriginReq) ProtoMessage()               {}
func (*UpdateOriginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateOriginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateOriginReq) GetDefaultPackageVisibility() string {
	if m != nil {
		return m.DefaultPackageVisibility
	}
	return ""
}

func init() {
	proto.RegisterType((*Origin)(nil), "hurtlocker.api.origins.request.Origin")
	proto.RegisterType((*GetOriginsReq)(nil), "hurtlocker.api.origins.request.GetOriginsReq")
	proto.RegisterType((*GetOriginReq)(nil), "hurtlocker.api.origins.request.GetOriginReq")
	proto.RegisterType((*CreateOriginReq)(nil), "hurtlocker.api.origins.request.CreateOriginReq")
	proto.RegisterType((*UpdateOriginReq)(nil), "hurtlocker.api.origins.request.UpdateOriginReq")
}

func init() {
	proto.RegisterFile("components/builder-gateway/api/origins/request/origins.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xbf, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x49, 0x94, 0x03, 0x17, 0x35, 0x90, 0x2a, 0x58, 0x88, 0xa4, 0xb2, 0x31, 0x5b, 0xd8,
	0x5e, 0xa5, 0x85, 0xa5, 0x1a, 0xd1, 0xc2, 0xe6, 0x98, 0xec, 0x8e, 0xc9, 0x98, 0x1f, 0xbb, 0xd9,
	0x9d, 0x55, 0xee, 0xbf, 0x17, 0x72, 0x77, 0xb9, 0xce, 0xc3, 0xc2, 0x6e, 0xf7, 0xcd, 0x07, 0xdf,
	0x83, 0x27, 0x96, 0xca, 0xf4, 0xd6, 0x0c, 0x38, 0xb0, 0x97, 0x55, 0xa0, 0x4e, 0xa3, 0xbb, 0xa9,
	0x81, 0xf1, 0x1b, 0xd6, 0x12, 0x2c, 0x49, 0xe3, 0xa8, 0xa6, 0xc1, 0x4b, 0x87, 0x63, 0x40, 0xcf,
	0xbb, 0x7f, 0x61, 0x9d, 0x61, 0x93, 0x5e, 0x36, 0xc1, 0x71, 0x67, 0x54, 0x8b, 0xae, 0x00, 0x4b,
	0xc5, 0xee, 0xba, 0xa5, 0xf3, 0x4f, 0xb1, 0x78, 0x9c, 0xa2, 0xf4, 0x5c, 0xc4, 0xa4, 0xb3, 0xe8,
	0x2a, 0xba, 0x3e, 0x29, 0x63, 0xd2, 0x69, 0x2a, 0x8e, 0x07, 0xe8, 0x31, 0x8b, 0xa7, 0x64, 0x7a,
	0xa7, 0x4b, 0x71, 0xa1, 0xf1, 0x03, 0x42, 0xc7, 0x2b, 0x0b, 0xaa, 0x85, 0x1a, 0x57, 0x5f, 0xe4,
	0xa9, 0xa2, 0x8e, 0x78, 0x9d, 0x1d, 0x4d, 0x64, 0xb6, 0x25, 0x9e, 0x36, 0xc0, 0xdb, 0x7c, 0xcf,
	0x13, 0x71, 0xf6, 0x80, 0xbc, 0xd1, 0xf9, 0x12, 0xc7, 0x3c, 0x17, 0xa7, 0x73, 0x50, 0xe2, 0x38,
	0x2b, 0xa3, 0xbd, 0x32, 0x57, 0x22, 0xb9, 0x77, 0x08, 0x8c, 0xbf, 0x62, 0x07, 0x9a, 0xc5, 0x07,
	0x9a, 0x29, 0x91, 0xbc, 0x5a, 0xfd, 0xbf, 0x92, 0xbb, 0x97, 0xf7, 0xe7, 0x9a, 0xb8, 0x09, 0x55,
	0xa1, 0x4c, 0x2f, 0x55, 0x13, 0x54, 0xdb, 0x61, 0x83, 0xa0, 0xbd, 0xdc, 0x8f, 0x24, 0xff, 0xb6,
	0x76, 0xb5, 0x98, 0x66, 0xbe, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xa3, 0xde, 0xcd, 0x26,
	0x02, 0x00, 0x00,
}
