// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/originsrv/origins/response/origins.proto

/*
Package response is a generated protocol buffer package.

It is generated from these files:
	components/originsrv/origins/response/origins.proto

It has these top-level messages:
	Origins
	OriginResp
	OriginsResp
*/
package response

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hurtlocker_originsrv_origins "github.com/chuckleheads/hurtlocker/components/originsrv/origins"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Origins struct {
	Origins []*hurtlocker_originsrv_origins.Origin `protobuf:"bytes,1,rep,name=origins" json:"origins,omitempty"`
}

func (m *Origins) Reset()                    { *m = Origins{} }
func (m *Origins) String() string            { return proto.CompactTextString(m) }
func (*Origins) ProtoMessage()               {}
func (*Origins) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Origins) GetOrigins() []*hurtlocker_originsrv_origins.Origin {
	if m != nil {
		return m.Origins
	}
	return nil
}

type OriginResp struct {
	Origin *hurtlocker_originsrv_origins.Origin `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
}

func (m *OriginResp) Reset()                    { *m = OriginResp{} }
func (m *OriginResp) String() string            { return proto.CompactTextString(m) }
func (*OriginResp) ProtoMessage()               {}
func (*OriginResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OriginResp) GetOrigin() *hurtlocker_originsrv_origins.Origin {
	if m != nil {
		return m.Origin
	}
	return nil
}

type OriginsResp struct {
	Origins *Origins `protobuf:"bytes,1,opt,name=origins" json:"origins,omitempty"`
}

func (m *OriginsResp) Reset()                    { *m = OriginsResp{} }
func (m *OriginsResp) String() string            { return proto.CompactTextString(m) }
func (*OriginsResp) ProtoMessage()               {}
func (*OriginsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OriginsResp) GetOrigins() *Origins {
	if m != nil {
		return m.Origins
	}
	return nil
}

func init() {
	proto.RegisterType((*Origins)(nil), "hurtlocker.originsrv.origins.response.Origins")
	proto.RegisterType((*OriginResp)(nil), "hurtlocker.originsrv.origins.response.OriginResp")
	proto.RegisterType((*OriginsResp)(nil), "hurtlocker.originsrv.origins.response.OriginsResp")
}

func init() {
	proto.RegisterFile("components/originsrv/origins/response/origins.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0xce, 0xcf, 0x2d,
	0xc8, 0xcf, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0xcf, 0x2f, 0xca, 0x4c, 0xcf, 0xcc, 0x2b, 0x2e, 0x2a,
	0x83, 0xb1, 0xf4, 0x8b, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x61, 0x02, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0xaa, 0x19, 0xa5, 0x45, 0x25, 0x39, 0xf9, 0xc9, 0xd9, 0xa9, 0x45, 0x7a,
	0x70, 0x4d, 0x30, 0x96, 0x1e, 0x4c, 0x93, 0x94, 0x16, 0x5e, 0xb3, 0x51, 0x8c, 0x54, 0xf2, 0xe4,
	0x62, 0xf7, 0x87, 0x08, 0x08, 0xd9, 0x71, 0xb1, 0x43, 0xe5, 0x24, 0x18, 0x15, 0x98, 0x35, 0xb8,
	0x8d, 0x54, 0xf4, 0xf0, 0xda, 0x07, 0xd1, 0x17, 0x04, 0xd3, 0xa4, 0xe4, 0xc5, 0xc5, 0x05, 0x15,
	0x4a, 0x2d, 0x2e, 0x10, 0xb2, 0xe1, 0x62, 0x83, 0x48, 0x48, 0x30, 0x2a, 0x30, 0x12, 0x6d, 0x18,
	0x54, 0x8f, 0x52, 0x38, 0x17, 0x37, 0xd4, 0x59, 0x60, 0xc3, 0x3c, 0x90, 0x9d, 0x06, 0x32, 0x4d,
	0x4f, 0x8f, 0xa8, 0xa0, 0xd0, 0x83, 0x19, 0x02, 0xd3, 0xee, 0xe4, 0x15, 0xe5, 0x91, 0x9e, 0x59,
	0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x9c, 0x51, 0x9a, 0x9c, 0x9d, 0x93, 0x9a,
	0x91, 0x9a, 0x98, 0x52, 0xac, 0x8f, 0x30, 0x51, 0x9f, 0xa8, 0xc8, 0x49, 0x62, 0x03, 0x07, 0xa1,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x02, 0x66, 0x3b, 0x9b, 0xcc, 0x01, 0x00, 0x00,
}
