// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/jobsrv/jobs/response/jobs.proto

/*
Package response is a generated protocol buffer package.

It is generated from these files:
	components/jobsrv/jobs/response/jobs.proto

It has these top-level messages:
	Job
	Jobs
	JobResp
	JobsResp
*/
package response

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Job) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Jobs struct {
	Jobs []*Job `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *Jobs) Reset()                    { *m = Jobs{} }
func (m *Jobs) String() string            { return proto.CompactTextString(m) }
func (*Jobs) ProtoMessage()               {}
func (*Jobs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Jobs) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type JobResp struct {
	Job *Job `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
}

func (m *JobResp) Reset()                    { *m = JobResp{} }
func (m *JobResp) String() string            { return proto.CompactTextString(m) }
func (*JobResp) ProtoMessage()               {}
func (*JobResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JobResp) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type JobsResp struct {
	Jobs *Jobs `protobuf:"bytes,1,opt,name=jobs" json:"jobs,omitempty"`
}

func (m *JobsResp) Reset()                    { *m = JobsResp{} }
func (m *JobsResp) String() string            { return proto.CompactTextString(m) }
func (*JobsResp) ProtoMessage()               {}
func (*JobsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JobsResp) GetJobs() *Jobs {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "hurtlocker.jobsrv.jobs.response.Job")
	proto.RegisterType((*Jobs)(nil), "hurtlocker.jobsrv.jobs.response.Jobs")
	proto.RegisterType((*JobResp)(nil), "hurtlocker.jobsrv.jobs.response.JobResp")
	proto.RegisterType((*JobsResp)(nil), "hurtlocker.jobsrv.jobs.response.JobsResp")
}

func init() { proto.RegisterFile("components/jobsrv/jobs/response/jobs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbd, 0x4b, 0xc4, 0x40,
	0x10, 0xc5, 0xc9, 0x07, 0x7e, 0x8c, 0x60, 0xb1, 0x55, 0x3a, 0x43, 0x50, 0x88, 0x16, 0xbb, 0xa0,
	0x20, 0xda, 0xe9, 0xa1, 0x4d, 0xca, 0x94, 0x76, 0xb7, 0x9b, 0xc1, 0xe4, 0xee, 0x92, 0x09, 0x3b,
	0x1b, 0xff, 0x7e, 0xd9, 0x39, 0xf4, 0xca, 0xbb, 0x6a, 0x66, 0x60, 0xde, 0xef, 0x3d, 0x1e, 0x3c,
	0x38, 0x1a, 0x67, 0x9a, 0x70, 0x0a, 0x6c, 0x36, 0x64, 0xd9, 0xff, 0xc8, 0x30, 0x1e, 0x79, 0xa6,
	0x89, 0x51, 0x2e, 0x3d, 0x7b, 0x0a, 0xa4, 0x6e, 0xfa, 0xc5, 0x87, 0x1d, 0xb9, 0x2d, 0x7a, 0xbd,
	0xff, 0x95, 0xa1, 0xff, 0x7e, 0xab, 0x7b, 0xc8, 0x1a, 0xb2, 0xea, 0x1a, 0xd2, 0xa1, 0x2b, 0x92,
	0x32, 0xa9, 0xb3, 0x36, 0x1d, 0x3a, 0xa5, 0x20, 0x9f, 0xd6, 0x23, 0x16, 0x69, 0x99, 0xd4, 0x97,
	0xad, 0xec, 0xd5, 0x1b, 0xe4, 0x0d, 0x59, 0x56, 0x2f, 0x90, 0x47, 0x46, 0x91, 0x94, 0x59, 0x7d,
	0xf5, 0x78, 0xab, 0x8f, 0x58, 0xe8, 0x86, 0x6c, 0x2b, 0x8a, 0xea, 0x1d, 0xce, 0xe3, 0x81, 0x3c,
	0xab, 0x67, 0xc8, 0x36, 0x64, 0xc5, 0xf1, 0x54, 0x46, 0x14, 0x54, 0x9f, 0x70, 0x11, 0x43, 0x08,
	0xe3, 0xf5, 0x3f, 0x48, 0x84, 0xdc, 0x9d, 0x02, 0xe1, 0x7d, 0x92, 0xd5, 0xc7, 0xd7, 0xea, 0x7b,
	0x08, 0xfd, 0x62, 0xb5, 0xa3, 0xd1, 0xb8, 0x7e, 0x71, 0xdb, 0x1d, 0xf6, 0xb8, 0xee, 0xd8, 0x1c,
	0x28, 0xe6, 0x48, 0xd1, 0xf6, 0x4c, 0x4a, 0x7e, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x91,
	0x0e, 0xee, 0x92, 0x01, 0x00, 0x00,
}
