// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/agent/proto/originsrv/originsrv.proto

/*
Package originsrv is a generated protocol buffer package.

TED TODO: This should be imported from OriginSrv

It is generated from these files:
	components/agent/proto/originsrv/originsrv.proto

It has these top-level messages:
	OriginPackageIdent
	OriginProject
	OriginSecret
	OriginSecretDecrypted
	OriginProjectIntegration
	OriginIntegration
*/
package originsrv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OriginPackageVisibility int32

const (
	OriginPackageVisibility_Public  OriginPackageVisibility = 0
	OriginPackageVisibility_Private OriginPackageVisibility = 1
	OriginPackageVisibility_Hidden  OriginPackageVisibility = 2
)

var OriginPackageVisibility_name = map[int32]string{
	0: "Public",
	1: "Private",
	2: "Hidden",
}
var OriginPackageVisibility_value = map[string]int32{
	"Public":  0,
	"Private": 1,
	"Hidden":  2,
}

func (x OriginPackageVisibility) String() string {
	return proto.EnumName(OriginPackageVisibility_name, int32(x))
}
func (OriginPackageVisibility) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OriginPackageIdent struct {
	Origin  string `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Release string `protobuf:"bytes,4,opt,name=release" json:"release,omitempty"`
}

func (m *OriginPackageIdent) Reset()                    { *m = OriginPackageIdent{} }
func (m *OriginPackageIdent) String() string            { return proto.CompactTextString(m) }
func (*OriginPackageIdent) ProtoMessage()               {}
func (*OriginPackageIdent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OriginPackageIdent) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *OriginPackageIdent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OriginPackageIdent) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *OriginPackageIdent) GetRelease() string {
	if m != nil {
		return m.Release
	}
	return ""
}

type OriginProject struct {
	Id                uint64                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	OriginId          uint64                  `protobuf:"varint,2,opt,name=origin_id,json=originId" json:"origin_id,omitempty"`
	OriginName        string                  `protobuf:"bytes,3,opt,name=origin_name,json=originName" json:"origin_name,omitempty"`
	PackageName       string                  `protobuf:"bytes,4,opt,name=package_name,json=packageName" json:"package_name,omitempty"`
	Name              string                  `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	PlanPath          string                  `protobuf:"bytes,6,opt,name=plan_path,json=planPath" json:"plan_path,omitempty"`
	OwnerId           uint64                  `protobuf:"varint,7,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
	VcsType           string                  `protobuf:"bytes,8,opt,name=vcs_type,json=vcsType" json:"vcs_type,omitempty"`
	VcsData           string                  `protobuf:"bytes,9,opt,name=vcs_data,json=vcsData" json:"vcs_data,omitempty"`
	VcsInstallationId uint32                  `protobuf:"varint,12,opt,name=vcs_installation_id,json=vcsInstallationId" json:"vcs_installation_id,omitempty"`
	Visibility        OriginPackageVisibility `protobuf:"varint,13,opt,name=visibility,enum=hurtlocker.agent.originsrv.OriginPackageVisibility" json:"visibility,omitempty"`
	AutoBuild         bool                    `protobuf:"varint,14,opt,name=auto_build,json=autoBuild" json:"auto_build,omitempty"`
}

func (m *OriginProject) Reset()                    { *m = OriginProject{} }
func (m *OriginProject) String() string            { return proto.CompactTextString(m) }
func (*OriginProject) ProtoMessage()               {}
func (*OriginProject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OriginProject) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OriginProject) GetOriginId() uint64 {
	if m != nil {
		return m.OriginId
	}
	return 0
}

func (m *OriginProject) GetOriginName() string {
	if m != nil {
		return m.OriginName
	}
	return ""
}

func (m *OriginProject) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *OriginProject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OriginProject) GetPlanPath() string {
	if m != nil {
		return m.PlanPath
	}
	return ""
}

func (m *OriginProject) GetOwnerId() uint64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *OriginProject) GetVcsType() string {
	if m != nil {
		return m.VcsType
	}
	return ""
}

func (m *OriginProject) GetVcsData() string {
	if m != nil {
		return m.VcsData
	}
	return ""
}

func (m *OriginProject) GetVcsInstallationId() uint32 {
	if m != nil {
		return m.VcsInstallationId
	}
	return 0
}

func (m *OriginProject) GetVisibility() OriginPackageVisibility {
	if m != nil {
		return m.Visibility
	}
	return OriginPackageVisibility_Public
}

func (m *OriginProject) GetAutoBuild() bool {
	if m != nil {
		return m.AutoBuild
	}
	return false
}

type OriginSecret struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	OriginId uint64 `protobuf:"varint,2,opt,name=origin_id,json=originId" json:"origin_id,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Value    string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *OriginSecret) Reset()                    { *m = OriginSecret{} }
func (m *OriginSecret) String() string            { return proto.CompactTextString(m) }
func (*OriginSecret) ProtoMessage()               {}
func (*OriginSecret) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OriginSecret) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OriginSecret) GetOriginId() uint64 {
	if m != nil {
		return m.OriginId
	}
	return 0
}

func (m *OriginSecret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OriginSecret) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type OriginSecretDecrypted struct {
	DecryptedSecret *OriginSecret `protobuf:"bytes,1,opt,name=decrypted_secret,json=decryptedSecret" json:"decrypted_secret,omitempty"`
}

func (m *OriginSecretDecrypted) Reset()                    { *m = OriginSecretDecrypted{} }
func (m *OriginSecretDecrypted) String() string            { return proto.CompactTextString(m) }
func (*OriginSecretDecrypted) ProtoMessage()               {}
func (*OriginSecretDecrypted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OriginSecretDecrypted) GetDecryptedSecret() *OriginSecret {
	if m != nil {
		return m.DecryptedSecret
	}
	return nil
}

type OriginProjectIntegration struct {
	Origin          string `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Integration     string `protobuf:"bytes,3,opt,name=integration" json:"integration,omitempty"`
	IntegrationName string `protobuf:"bytes,4,opt,name=integration_name,json=integrationName" json:"integration_name,omitempty"`
	Body            string `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
}

func (m *OriginProjectIntegration) Reset()                    { *m = OriginProjectIntegration{} }
func (m *OriginProjectIntegration) String() string            { return proto.CompactTextString(m) }
func (*OriginProjectIntegration) ProtoMessage()               {}
func (*OriginProjectIntegration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OriginProjectIntegration) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *OriginProjectIntegration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OriginProjectIntegration) GetIntegration() string {
	if m != nil {
		return m.Integration
	}
	return ""
}

func (m *OriginProjectIntegration) GetIntegrationName() string {
	if m != nil {
		return m.IntegrationName
	}
	return ""
}

func (m *OriginProjectIntegration) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type OriginIntegration struct {
	Origin      string `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Integration string `protobuf:"bytes,2,opt,name=integration" json:"integration,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Body        string `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
}

func (m *OriginIntegration) Reset()                    { *m = OriginIntegration{} }
func (m *OriginIntegration) String() string            { return proto.CompactTextString(m) }
func (*OriginIntegration) ProtoMessage()               {}
func (*OriginIntegration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *OriginIntegration) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *OriginIntegration) GetIntegration() string {
	if m != nil {
		return m.Integration
	}
	return ""
}

func (m *OriginIntegration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OriginIntegration) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*OriginPackageIdent)(nil), "hurtlocker.agent.originsrv.OriginPackageIdent")
	proto.RegisterType((*OriginProject)(nil), "hurtlocker.agent.originsrv.OriginProject")
	proto.RegisterType((*OriginSecret)(nil), "hurtlocker.agent.originsrv.OriginSecret")
	proto.RegisterType((*OriginSecretDecrypted)(nil), "hurtlocker.agent.originsrv.OriginSecretDecrypted")
	proto.RegisterType((*OriginProjectIntegration)(nil), "hurtlocker.agent.originsrv.OriginProjectIntegration")
	proto.RegisterType((*OriginIntegration)(nil), "hurtlocker.agent.originsrv.OriginIntegration")
	proto.RegisterEnum("hurtlocker.agent.originsrv.OriginPackageVisibility", OriginPackageVisibility_name, OriginPackageVisibility_value)
}

func init() { proto.RegisterFile("components/agent/proto/originsrv/originsrv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5b, 0x6f, 0xd3, 0x30,
	0x18, 0x25, 0x5d, 0xd7, 0xcb, 0xd7, 0x5d, 0x3a, 0x73, 0x0b, 0x4c, 0x88, 0xd2, 0xa7, 0xc2, 0x43,
	0x8a, 0xb6, 0x77, 0x1e, 0xc6, 0x90, 0xc8, 0x0b, 0x54, 0x19, 0xe2, 0x81, 0x97, 0xca, 0xb1, 0x3f,
	0x35, 0x66, 0xa9, 0x1d, 0x39, 0x4e, 0x50, 0xff, 0x10, 0xfc, 0x4d, 0x14, 0x3b, 0x69, 0x33, 0x60,
	0x1a, 0x7b, 0xcb, 0x39, 0xc7, 0xf6, 0x39, 0xdf, 0x45, 0x81, 0xb7, 0x4c, 0xad, 0x33, 0x25, 0x51,
	0x9a, 0x7c, 0x4e, 0x57, 0x28, 0xcd, 0x3c, 0xd3, 0xca, 0xa8, 0xb9, 0xd2, 0x62, 0x25, 0x64, 0xae,
	0xcb, 0xdd, 0x57, 0x60, 0x15, 0xf2, 0x3c, 0x29, 0xb4, 0x49, 0x15, 0xbb, 0x46, 0x1d, 0xd8, 0x1b,
	0xc1, 0xf6, 0xc4, 0xd4, 0x00, 0xf9, 0x6c, 0xc1, 0x82, 0xb2, 0x6b, 0xba, 0xc2, 0x90, 0xa3, 0x34,
	0xe4, 0x09, 0xf4, 0xdc, 0x11, 0xdf, 0x9b, 0x78, 0xb3, 0x61, 0x54, 0x23, 0x42, 0xa0, 0x2b, 0xe9,
	0x1a, 0xfd, 0x8e, 0x65, 0xed, 0x37, 0xf1, 0xa1, 0x5f, 0xa2, 0xce, 0x85, 0x92, 0xfe, 0x9e, 0xa5,
	0x1b, 0x58, 0x29, 0x1a, 0x53, 0xa4, 0x39, 0xfa, 0x5d, 0xa7, 0xd4, 0x70, 0xfa, 0x73, 0x0f, 0x0e,
	0x6b, 0x5b, 0xad, 0xbe, 0x23, 0x33, 0xe4, 0x08, 0x3a, 0x82, 0x5b, 0xb7, 0x6e, 0xd4, 0x11, 0x9c,
	0x9c, 0xc2, 0xd0, 0x79, 0x2e, 0x05, 0xb7, 0x76, 0xdd, 0x68, 0xe0, 0x88, 0x90, 0x93, 0x97, 0x30,
	0xaa, 0x45, 0x9b, 0xc6, 0xd9, 0x82, 0xa3, 0x3e, 0x55, 0x99, 0x5e, 0xc1, 0x41, 0xe6, 0xea, 0x71,
	0x27, 0x9c, 0xfd, 0xa8, 0xe6, 0xec, 0x91, 0xa6, 0x94, 0xfd, 0x56, 0x29, 0xa7, 0x30, 0xcc, 0x52,
	0x2a, 0x97, 0x19, 0x35, 0x89, 0xdf, 0xb3, 0xc2, 0xa0, 0x22, 0x16, 0xd4, 0x24, 0xe4, 0x19, 0x0c,
	0xd4, 0x0f, 0x89, 0xba, 0x0a, 0xd4, 0xb7, 0x81, 0xfa, 0x16, 0x87, 0xbc, 0x92, 0x4a, 0x96, 0x2f,
	0xcd, 0x26, 0x43, 0x7f, 0x50, 0xf7, 0x80, 0xe5, 0x5f, 0x36, 0x19, 0x36, 0x12, 0xa7, 0x86, 0xfa,
	0xc3, 0xad, 0x74, 0x49, 0x0d, 0x25, 0x01, 0x3c, 0xac, 0x24, 0x21, 0x73, 0x43, 0xd3, 0x94, 0x1a,
	0xa1, 0x6c, 0xb1, 0x07, 0x13, 0x6f, 0x76, 0x18, 0x9d, 0x94, 0x2c, 0x0f, 0x5b, 0x4a, 0xc8, 0xc9,
	0x15, 0x40, 0x29, 0x72, 0x11, 0x8b, 0x54, 0x98, 0x8d, 0x7f, 0x38, 0xf1, 0x66, 0x47, 0x67, 0xe7,
	0xc1, 0xed, 0xb3, 0x0d, 0x6e, 0x0c, 0xf6, 0xeb, 0xf6, 0x6a, 0xd4, 0x7a, 0x86, 0xbc, 0x00, 0xa0,
	0x85, 0x51, 0xcb, 0xb8, 0x10, 0x29, 0xf7, 0x8f, 0x26, 0xde, 0x6c, 0x10, 0x0d, 0x2b, 0xe6, 0xa2,
	0x22, 0xa6, 0x08, 0x07, 0xee, 0x95, 0x2b, 0x64, 0x1a, 0xef, 0x39, 0xa6, 0xa6, 0xc5, 0x7b, 0xad,
	0x16, 0x3f, 0x82, 0xfd, 0x92, 0xa6, 0x45, 0x33, 0x12, 0x07, 0xa6, 0x29, 0x3c, 0x6e, 0xdb, 0x5c,
	0x22, 0xd3, 0x9b, 0xcc, 0x60, 0x55, 0xf3, 0x98, 0x37, 0x60, 0x99, 0x5b, 0xd1, 0xba, 0x8f, 0xce,
	0x66, 0x77, 0x57, 0xee, 0x1e, 0x8b, 0x8e, 0xb7, 0x2f, 0x38, 0x62, 0xfa, 0xcb, 0x03, 0xff, 0xc6,
	0xf6, 0x85, 0xd2, 0xe0, 0x4a, 0xdb, 0x3e, 0xdf, 0x6b, 0xf5, 0x27, 0x30, 0x12, 0xbb, 0xab, 0x75,
	0x9d, 0x6d, 0x8a, 0xbc, 0x86, 0x71, 0x0b, 0xb6, 0x97, 0xf1, 0xb8, 0xc5, 0x37, 0x0b, 0x19, 0x2b,
	0xbe, 0x69, 0x16, 0xb2, 0xfa, 0x9e, 0x16, 0x70, 0xe2, 0x82, 0xfe, 0x4f, 0xc2, 0x3f, 0xd2, 0x74,
	0xfe, 0x4e, 0xf3, 0xaf, 0x81, 0x34, 0xb6, 0xdd, 0x9d, 0xed, 0x9b, 0x77, 0xf0, 0xf4, 0x96, 0xdd,
	0x21, 0x00, 0xbd, 0x45, 0x11, 0xa7, 0x82, 0x8d, 0x1f, 0x90, 0x11, 0xf4, 0x17, 0x5a, 0x94, 0xd4,
	0xe0, 0xd8, 0xab, 0x84, 0x8f, 0x82, 0x73, 0x94, 0xe3, 0xce, 0xc5, 0x87, 0x6f, 0xef, 0x57, 0xc2,
	0x24, 0x45, 0x1c, 0x30, 0xb5, 0x9e, 0xb3, 0xa4, 0x60, 0xd7, 0x29, 0x26, 0x48, 0x79, 0x3e, 0xdf,
	0x0d, 0x6d, 0x7e, 0xd7, 0x7f, 0x2c, 0xee, 0x59, 0xe2, 0xfc, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x79, 0x5f, 0x87, 0x17, 0xf2, 0x04, 0x00, 0x00,
}
