// Code generated by protoc-gen-go. DO NOT EDIT.
// source: components/gateway/api/origins/origins.proto

/*
Package origins is a generated protocol buffer package.

It is generated from these files:
	components/gateway/api/origins/origins.proto

It has these top-level messages:
*/
package origins

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import hurtlocker_originsrv_origins_request "github.com/chuckleheads/hurtlocker/components/originsrv/origins/request"
import hurtlocker_originsrv_origins_response "github.com/chuckleheads/hurtlocker/components/originsrv/origins/response"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Origins service

type OriginsClient interface {
	GetOrigin(ctx context.Context, in *hurtlocker_originsrv_origins_request.GetOriginReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_origins_response.OriginResp, error)
	CreateOrigin(ctx context.Context, in *hurtlocker_originsrv_origins_request.CreateOriginReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_origins_response.OriginResp, error)
	UpdateOrigin(ctx context.Context, in *hurtlocker_originsrv_origins_request.UpdateOriginReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_origins_response.OriginResp, error)
}

type originsClient struct {
	cc *grpc.ClientConn
}

func NewOriginsClient(cc *grpc.ClientConn) OriginsClient {
	return &originsClient{cc}
}

func (c *originsClient) GetOrigin(ctx context.Context, in *hurtlocker_originsrv_origins_request.GetOriginReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_origins_response.OriginResp, error) {
	out := new(hurtlocker_originsrv_origins_response.OriginResp)
	err := grpc.Invoke(ctx, "/hurtlocker.api.origins.Origins/GetOrigin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *originsClient) CreateOrigin(ctx context.Context, in *hurtlocker_originsrv_origins_request.CreateOriginReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_origins_response.OriginResp, error) {
	out := new(hurtlocker_originsrv_origins_response.OriginResp)
	err := grpc.Invoke(ctx, "/hurtlocker.api.origins.Origins/CreateOrigin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *originsClient) UpdateOrigin(ctx context.Context, in *hurtlocker_originsrv_origins_request.UpdateOriginReq, opts ...grpc.CallOption) (*hurtlocker_originsrv_origins_response.OriginResp, error) {
	out := new(hurtlocker_originsrv_origins_response.OriginResp)
	err := grpc.Invoke(ctx, "/hurtlocker.api.origins.Origins/UpdateOrigin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Origins service

type OriginsServer interface {
	GetOrigin(context.Context, *hurtlocker_originsrv_origins_request.GetOriginReq) (*hurtlocker_originsrv_origins_response.OriginResp, error)
	CreateOrigin(context.Context, *hurtlocker_originsrv_origins_request.CreateOriginReq) (*hurtlocker_originsrv_origins_response.OriginResp, error)
	UpdateOrigin(context.Context, *hurtlocker_originsrv_origins_request.UpdateOriginReq) (*hurtlocker_originsrv_origins_response.OriginResp, error)
}

func RegisterOriginsServer(s *grpc.Server, srv OriginsServer) {
	s.RegisterService(&_Origins_serviceDesc, srv)
}

func _Origins_GetOrigin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hurtlocker_originsrv_origins_request.GetOriginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OriginsServer).GetOrigin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hurtlocker.api.origins.Origins/GetOrigin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OriginsServer).GetOrigin(ctx, req.(*hurtlocker_originsrv_origins_request.GetOriginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Origins_CreateOrigin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hurtlocker_originsrv_origins_request.CreateOriginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OriginsServer).CreateOrigin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hurtlocker.api.origins.Origins/CreateOrigin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OriginsServer).CreateOrigin(ctx, req.(*hurtlocker_originsrv_origins_request.CreateOriginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Origins_UpdateOrigin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hurtlocker_originsrv_origins_request.UpdateOriginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OriginsServer).UpdateOrigin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hurtlocker.api.origins.Origins/UpdateOrigin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OriginsServer).UpdateOrigin(ctx, req.(*hurtlocker_originsrv_origins_request.UpdateOriginReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Origins_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hurtlocker.api.origins.Origins",
	HandlerType: (*OriginsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrigin",
			Handler:    _Origins_GetOrigin_Handler,
		},
		{
			MethodName: "CreateOrigin",
			Handler:    _Origins_CreateOrigin_Handler,
		},
		{
			MethodName: "UpdateOrigin",
			Handler:    _Origins_UpdateOrigin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "components/gateway/api/origins/origins.proto",
}

func init() { proto.RegisterFile("components/gateway/api/origins/origins.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xbd, 0x4a, 0xf4, 0x40,
	0x14, 0x86, 0xc9, 0xf7, 0x81, 0x3f, 0x61, 0x45, 0x1c, 0x45, 0x21, 0x58, 0x6d, 0xb9, 0xc8, 0x0c,
	0x66, 0xb1, 0xd9, 0x4e, 0xb7, 0xb0, 0x14, 0x04, 0x1b, 0xbb, 0xd9, 0xec, 0x21, 0x19, 0x36, 0x99,
	0x33, 0x3b, 0x73, 0xa2, 0x88, 0xd8, 0xd8, 0x8a, 0x95, 0x5e, 0x8f, 0x37, 0xe1, 0x2d, 0x78, 0x21,
	0x42, 0x92, 0x89, 0x59, 0x0b, 0x57, 0xb7, 0x9a, 0x3f, 0x9e, 0x79, 0x1f, 0x0e, 0x6f, 0x78, 0x94,
	0x60, 0x61, 0x50, 0x83, 0x26, 0x27, 0x52, 0x49, 0x70, 0x2b, 0xef, 0x84, 0x34, 0x4a, 0xa0, 0x55,
	0xa9, 0xd2, 0xce, 0xaf, 0xdc, 0x58, 0x24, 0x64, 0xfb, 0x59, 0x69, 0x29, 0xc7, 0x64, 0x06, 0x96,
	0x4b, 0xa3, 0x78, 0xf3, 0x1a, 0x1d, 0xa6, 0x88, 0x69, 0x0e, 0x15, 0x29, 0xb5, 0x46, 0x92, 0xa4,
	0xd0, 0x53, 0x51, 0xdc, 0xc9, 0x68, 0x08, 0x7b, 0xd3, 0x26, 0x58, 0x98, 0x97, 0xe0, 0x68, 0x31,
	0x29, 0x1a, 0x2e, 0x61, 0x9c, 0x41, 0xed, 0x60, 0x11, 0x8a, 0xdf, 0xfe, 0x87, 0xeb, 0x17, 0xf5,
	0x0d, 0x7b, 0x0a, 0xc2, 0xcd, 0x73, 0xa0, 0xfa, 0xc8, 0x62, 0xde, 0x31, 0x6f, 0xff, 0xf3, 0x3b,
	0xde, 0x38, 0xf0, 0x16, 0xb8, 0x84, 0x79, 0x74, 0xbc, 0x8c, 0xa9, 0x1d, 0xb8, 0x27, 0x9c, 0xe9,
	0x1f, 0x3c, 0xbe, 0x7f, 0xbc, 0xfc, 0xdb, 0x61, 0xdb, 0xad, 0xe9, 0xbd, 0x96, 0x05, 0x3c, 0xb0,
	0xe7, 0x20, 0xec, 0x8d, 0x2d, 0x48, 0x82, 0x46, 0xe8, 0xe4, 0x77, 0x42, 0x5d, 0x66, 0x45, 0xa7,
	0xdd, 0xca, 0x69, 0xab, 0xbf, 0xe1, 0x9d, 0x46, 0xc1, 0x80, 0xbd, 0x06, 0x61, 0xef, 0xca, 0x4c,
	0xff, 0xec, 0xd3, 0x65, 0x56, 0xf4, 0x89, 0x2a, 0x9f, 0xbd, 0xf8, 0xfb, 0x8c, 0x46, 0xc1, 0xe0,
	0x6c, 0x7c, 0x7d, 0x9a, 0x2a, 0xca, 0xca, 0x09, 0x4f, 0xb0, 0x10, 0x49, 0x56, 0x26, 0xb3, 0x1c,
	0x32, 0x90, 0x53, 0x27, 0xbe, 0x72, 0xc4, 0xcf, 0x95, 0x9d, 0xac, 0x55, 0x65, 0x18, 0x7e, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xfc, 0x82, 0x62, 0xb9, 0xdb, 0x02, 0x00, 0x00,
}
